### ISSUE TITLE
/help command crashes

### ISSUE THREAD

**Issue by Zifius** [Zifius/telegram-knowledgebase-bot#15]
> 2019-01-30 21:22:29,925 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
TypeError: __call__() takes from 1 to 2 positional arguments but 3 were given

**Comment by frostygrizzly** [comment]
https://github.com/Zifius/telegram-knowledgebase-bot/pull/18
